PoC/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import render
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('workflows/', include('workflows.urls')), #if the user requests the homepage include all the URLS from the workflows file. root domain
    path('', include('users.urls')) #if the user requests the homepage include all the URLS from the workflows file. root domain


]



urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path
from . import views



urlpatterns = [
    path('', views.profiles, name="profiles"),
    path('profile/<str:pk>', views.userProfile, name="user-profile"),

]

users/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid
# Create your models here.

from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver


class Profile(models.Model):
    user = models.ManyToManyField(User, blank=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    email = models.EmailField(max_length=500, blank=True, null=True)
    username = models.CharField(max_length=200, blank=True, null=True)
    location = models.CharField(max_length=200, blank=True, null=True)
    short_intro = models.CharField(max_length=200, blank=True, null=True)
    bio = models.TextField(blank=True, null=True)
    profile_image = models.ImageField(
        null=True, blank=True, upload_to='profiles/', default="profiles/user-default.png")
    social_github = models.CharField(max_length=200, blank=True, null=True)
    social_twitter = models.CharField(max_length=200, blank=True, null=True)
    social_linkedin = models.CharField(max_length=200, blank=True, null=True)
    social_youtube = models.CharField(max_length=200, blank=True, null=True)
    social_website = models.CharField(max_length=200, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.AutoField(primary_key=True, editable=False, unique=True)


    def __str__(self):
        return str(self.username)

    class Meta:
        ordering = ['created']

    @property
    def imageURL(self):
        try:
            url = self.profile_image.url
        except:
            url = ''
        return url


class Skill(models.Model):
    owner = models.ForeignKey(
        Profile, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    description = models.TextField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.AutoField(primary_key=True, editable=False, unique=True)


    def __str__(self):
        return str(self.name)


class Message(models.Model):
    sender = models.ForeignKey(
        Profile, on_delete=models.SET_NULL, null=True, blank=True)
    recipient = models.ForeignKey(
        Profile, on_delete=models.SET_NULL, null=True, blank=True, related_name="messages")
    name = models.CharField(max_length=200, null=True, blank=True)
    email = models.EmailField(max_length=200, null=True, blank=True)
    subject = models.CharField(max_length=200, null=True, blank=True)
    body = models.TextField()
    is_read = models.BooleanField(default=False, null=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.AutoField(primary_key=True, editable=False, unique=True)

    def __str__(self):
        return self.subject

    class Meta:
        ordering = ['is_read', '-created']

workflows/models.py
from telnetlib import STATUS
from unicodedata import name
from django.db import models
from users.models import Profile



# Create your models here.
# django4 supports multiple db's

class Workflow(models.Model):
    id = models.AutoField(primary_key=True, editable=False)
    name = models.CharField(max_length=50)
    description = models.TextField(null=True, blank=True, max_length=30)
    featured_image = models.ImageField(
        null=True, blank=True, default="default.jpg")
    tags = models.ManyToManyField('Tag', blank=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now_add=True)
    retired = models.BooleanField(default=False)
    # Foreign Keys
    owner = models.ManyToManyField(Profile, blank=True)
    status = models.ForeignKey('Status',on_delete=models.CASCADE)
    steps = models.ManyToManyField('Steps', blank=True)

    
    # status = models.ForeignKey('Status', blank=True,  on_delete=models.CASCADE)
    # tags = models.ManyToManyField('Tag', blank=True, related_name='workflows') 
    # created_by = 
    # requester_id
        
    def __str__(self):
        return self.name

    @property
    def imageURL(self):
        try:
            url = self.featured_image.url
        except:
            url = ''
        return url
    
        #foreign key 1 to many relationship
class Review(models.Model):
    #owner = 
    workflow = models.ForeignKey(Workflow, on_delete=models.CASCADE)
    body = models.TextField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.AutoField(primary_key=True, editable=False)
    
    def __str__(self):
        return f'workflow: {self.workflow} {self.created}'
    
    
    
    
#many to many relationship with Workflow
class Tag(models.Model):
    name = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    id = models.AutoField(primary_key=True, editable=False)
    
    def __str__(self):
        return self.name

#many to many relationship with Workflow
class Status(models.Model):
    name = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    id = models.AutoField(primary_key=True, editable=False)
    
    def __str__(self):
        return self.name
    
    
class Steps(models.Model):
    owner = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True, blank=True)
    id = models.AutoField(primary_key=True, editable=False)
    name = models.CharField(max_length=50)
    description = models.TextField(null=True, blank=True, max_length=30)
    tags = models.ManyToManyField('Tag', blank=True)
    # status = models.ForeignKey('Status',on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now_add=True)
    retired = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
       
       
    def __str__(self):
        return self.name

    
    # status = models.ForeignKey('Status', blank=True,  on_delete=models.CASCADE)
    # tags = models.ManyToManyField('Tag', blank=True, related_name='workflows') 
    # created_by = 
    # requester_id
        
 
    
    
#many to many relationship
# Tag to be easily identifiable.
# class Tag(models.Model):
#     name = models.CharField('Workflow', max_length=200, null=True)
#     created = models.DateTimeField(auto_now_add=True)
#     id = models.AutoField(primary_key=True, editable=False)
    
#     def __str__(self):
#         return self.name
    
#    #i want the status/states to be selectable 
# class Status(models.Model):
#     name = models.CharField(Workflow,max_length=200)
#     created = models.DateTimeField(auto_now_add=True)
#     id = models.AutoField(primary_key=True, editable=False)
    


    
#     def __str__(self):
#         return self.name
    
  

users/views.py
from django.shortcuts import render
from . models import Profile

# Create your views here.
def profiles(request):
    profiles = Profile.objects.all()
    context = {'profiles': profiles}
    return render(request, 'users/profiles.html', context)


def userProfile(request, pk):
    profile = Profile.objects.get(id=pk)

    topSkills = profile.skill_set.exclude(description__exact="")
    otherSkills = profile.skill_set.filter(description="")

    context = {'profile': profile, 'topSkills': topSkills,
               "otherSkills": otherSkills}
    return render(request, 'users/user-profile.html', context)


users/templates/users/profiles.html
{% extends 'base.html' %}

{% block body %}


<!-- Main Section -->
<main class="home">
    <section class="hero-section text-center">
        <div class="container container--narrow">
            <div class="hero-section__box">
                <h2>CONNECT WITH <span>DEVELOPERS</span></h2>
                <h2>FROM AROUND THE WORLD</h2>
            </div>

            <div class="hero-section__search">

                <form id="searchForm" class="form" action="{% url 'profiles' %}" method="get">
                    <div class="form__field">
                        <label for="formInput#search">Search Developers </label>
                        <input class="input input--text" id="formInput#search" type="text" name="search_query"
                            value="{{search_query}}" placeholder="Search by developer name" />
                    </div>

                    <input class="btn btn--sub btn--lg" type="submit" value="Search" />
                </form>

            </div>
        </div>
    </section>
    <!-- Search Result: DevList -->
    <section class="devlist">
        <div class="container">
            <div class="grid grid--three">

                {% for profile in profiles %}
                <div class="column card">
                    <div class="dev">
                        <a href="{% url 'user-profile' profile.id %}" class="card__body">
                            <div class="dev__profile">
                                <img class="avatar avatar--md" src="{{ profile.profile_image.url }}" alt="image" />
                                <div class="dev__meta">
                                    <h3>{{profile.name}}</h3>
                                    <h5>{{profile.short_intro|slice:"60"}}</h5>
                                </div>
                            </div>
                            <p class="dev__info">{{profile.bio|slice:"150"}}</p>
                            <div class="dev__skills">

                                {% for skill in profile.skill_set.all|slice:"5" %}
                                <span class="tag tag--pill tag--main">
                                    <small>{{skill}}</small>
                                </span>
                                {% endfor %}

                            </div>
                        </a>
                    </div>
                </div>
                {% endfor %}

            </div>
        </div>
    </section>

    </main>

{% endblock body %}

users/templates/users/user-profile.html
{% extends 'base.html' %}

{% block body %}

<!-- Main Section -->
<main class="profile my-md">
    <div class="container">
        <div class="layout">
            <div class="column column--1of3">
                <div class="card text-center">
                    <div class="card__body dev">
                        <img class="avatar avatar--xl" src="{{ profile.imageURL }}" />
                        <h2 class="dev__name">{{profile.name}}</h2>
                        <p class="dev__title">{{profile.short_intro}}</p>
                        <p class="dev__location">Based in {{profile.location}}</p>
                        <ul class="dev__social">

                            {% if profile.social_github %}
                            <li>
                                <a title="Github" href="{{profile.social_github}}" target="_blank"><i
                                        class="im im-github"></i></a>
                            </li>
                            {% endif %}


                            {% if profile.social_twitter %}
                            <li>
                                <a title="Twitter" href="{{profile.social_twitter}}" target="_blank"><i
                                        class="im im-twitter"></i></a>
                            </li>
                            {% endif %}

                            {% if profile.social_linkedin %}
                            <li>
                                <a title="LinkedIn" href="{{profile.social_linkedin}}" target="_blank"><i
                                        class="im im-linkedin"></i></a>
                            </li>
                            {% endif %}

                            {% if profile.social_website %}
                            <li>
                                <a title="Personal Website" href="{{profile.social_website}}" target="_blank"><i
                                        class="im im-globe"></i></a>
                            </li>
                            {% endif %}

                        </ul>
                        {% comment %} {% if request.user.profile.id != profile.id %}
                        <a href="{% url 'create-message' profile.id %}" class="btn btn--sub btn--lg">Send Message </a>
                        {% endif %} {% endcomment %}
                    </div>
                </div>
            </div>
            <div class="column column--2of3">
                <div class="devInfo">
                    <h3 class="devInfo__title">About Me</h3>
                    <p class="devInfo__about">{{profile.bio}}</p>
                </div>
                <div class="devInfo">
                    <h3 class="devInfo__title">Skills</h3>
                    <div class="devInfo__skills">

                        {% for skill in topSkills %}
                        <div class="devSkill">
                            <h4 class="devSkill__title">{{skill.name}}</h4>
                            <p class="devSkill__info">{{skill.description}}</p>
                        </div>
                        {% endfor %}



              <h3 class="devInfo__subtitle">Other Skills</h3>
              <div class="devInfo__otherSkills">
                {% for skill in otherSkills %}
                <span class="tag tag--pill tag--sub tag--lg">
                  <small>{{ skill }}</small>
                </span>
                {% endfor %}
              </div>
            </div>
          </div>
          <div class="devInfo">
            <h3 class="devInfo__title">Workflows:</h3>
            <div class="grid grid--two">
                {% for workflow in profile.workflow_set.all %}
                <div class="column">
                    <div class="card project">
                        <a href="{% url 'workflow' workflow.id %}" class="project">
                            <div class="dev__profile">

                            <img class="project" src="{{workflow.featured_image.url}}"
                                alt="project thumbnail" />
                            <div class="card__body">
                                <h3 class="project__title">{{workflow.name}}</h3>
                   
                                </p>
                               
                                <div class="project__tags">

                                    {% for tag in workflow.tags.all %}
                                    <span class="tag tag--pill tag--main">
                                        <small>{{tag}}</small>
                                    </span>
                                    {% endfor %}

                                </div>
                            </div>
                        </a>
                    </div>
                </div>
                {% endfor %}

                    </div>
                </div>
            </div>
        </div>
    </div>
</main>

{% endblock body %}